### ISSUE TITLE
Failing to connect to the wallet client, errors in ag-solo logs

### ISSUE THREAD

**Issue by Syd-ai** [Agoric/dapp-treasury#31]
Hello,

I have some trouble to connect to the client. It seems I'm trying to connect but it gets terminated each time. On Brower I see some quick connections and disconnections.

Tried to restart the ag-solo docker
Tried to restart with -v flag
Tried to reinstall docker compose and engine

Nothing seems to work.

Logs attached,
Thanks!

[docker-compose logs.txt](https://github.com/Agoric/dapp-treasury/files/6463637/docker-compose.logs.txt)

**Comment by migimigi** [comment]
I have the same problem.
Error after registering a client with Agoric discord faucet.

```
ag-solo_1  | 2021-05-12T02:21:36.569Z start: swingset running
ag-solo_1  | 2021-05-12T02:21:36.571Z outbound: invoking deliverator; 1 new messages for 7541da1915ab72a2773b11cd6e17454732e6bb895b78daeef8618ae8ff182e9c
ag-solo_1  | 2021-05-12T02:21:37.572Z chain-cosmos-sdk: delivering to chain (trips=1) 7541da1915ab72a2773b11cd6e17454732e6bb895b78daeef8618ae8ff182e9c [ [ 1, '1:0:deliver:ro+1:getDemoBundle:rp-40;[]' ] ] 0
ag-solo_1  | 2021-05-12T02:21:38.193Z chain-cosmos-sdk: could not find peer mailbox - agoric15tty9rwuzsh2mu9lugj49r2s85am52rr8muuuk: rpc error: code = Unknown desc = could not get peer mailbox: unknown request
ag-solo_1  | Open CapTP connection to ws://0.0.0.0:8000/private/captp...2021-05-12T02:21:43.092Z web: 127.0.0.1:40736[1]: new WebSocket /private/captp?accessToken=vkcQfi8K1RvSRWNv2-WB6ctJ10QjnX8y0490Nyoad4ypTV5BDpAEIF-C0Itc0aud
ag-solo_1  | 2021-05-12T02:21:43.334Z chain-cosmos-sdk: gas estimate: 48982
ag-solo_1  | 2021-05-12T02:21:43.512Z chain-cosmos-sdk: could not find peer mailbox - agoric15tty9rwuzsh2mu9lugj49r2s85am52rr8muuuk: rpc error: code = Unknown desc = could not get peer mailbox: unknown request
ag-solo_1  | ooo2021-05-12T02:21:44.235Z SwingSet: ls: v5: Logging sent error stack (RemoteError(error:liveSlots:v8#70005)#1)
ag-solo_1  | RemoteError(error:liveSlots:v8#70005)#1: vat terminated
ag-solo_1  |
ag-solo_1  |   at fullRevive (packages/marshal/src/marshal.js:526:43)
ag-solo_1  |   at meteredConstructor.unserialize (packages/marshal/src/marshal.js:609:19)
ag-solo_1  |   at notifyOnePromise (packages/SwingSet/src/kernel/liveSlots.js:720:19)
ag-solo_1  |   at notify (packages/SwingSet/src/kernel/liveSlots.js:733:7)
ag-solo_1  |   at dispatchToUserspace (packages/SwingSet/src/kernel/liveSlots.js:843:11)
ag-solo_1  |
ag-solo_1  | RemoteError(error:liveSlots:v8#70005)#1 ERROR_NOTE: Rejection from: (Error#2) : 42 . 0
ag-solo_1  | RemoteError(error:liveSlots:v8#70005)#1 ERROR_NOTE: Rejection from: (Error#3) : 1 . 1
ag-solo_1  | RemoteError(error:liveSlots:v8#70005)#1 ERROR_NOTE: Sent as error:liveSlots:v5#70001
ag-solo_1  | Nested 2 errors under RemoteError(error:liveSlots:v8#70005)#1
ag-solo_1  |   Error#2: Event: 41.1
ag-solo_1  |
ag-solo_1  |     at Function.applyMethod (packages/tame-metering/src/tame.js:184:20)
ag-solo_1  |     at Proxy.eval (packages/eventual-send/src/E.js:37:49)
ag-solo_1  |     at Alleged: root.bootstrap (packages/vats/src/bootstrap.js:870:57)
ag-solo_1  |
ag-solo_1  |   Error#3: Event: 0.1
ag-solo_1  |
ag-solo_1  |     at Function.applyMethod (packages/tame-metering/src/tame.js:184:20)
ag-solo_1  |     at deliver (packages/SwingSet/src/kernel/liveSlots.js:644:28)
ag-solo_1  |     at dispatchToUserspace (packages/SwingSet/src/kernel/liveSlots.js:838:11)
ag-solo_1  |
ag-solo_1  | 2021-05-12T02:21:44.250Z SwingSet: kernel: ##### KERNEL PANIC: kp40.policy panic: rejected {"body":"{\"@qclass\":\"error\",\"errorId\":\"error:liveSlots:v5#70001\",\"message\":\"vat terminated\",\"name\":\"Error\"}","slots":[]} #####
ag-solo_1  | UnhandledPromiseRejectionWarning: (Error#4)
ag-solo_1  | Error#4: kernel panic kp40.policy panic: rejected {"body":"{\"@qclass\":\"error\",\"errorId\":\"error:liveSlots:v5#70001\",\"message\":\"vat terminated\",\"name\":\"Error\"}","slots":[]}
ag-solo_1  |
ag-solo_1  |   at panic (packages/SwingSet/src/kernel/kernel.js:233:26)
ag-solo_1  |   at doResolve (packages/SwingSet/src/kernel/kernel.js:305:9)
ag-solo_1  |   at resolve (packages/SwingSet/src/kernel/kernelSyscall.js:112:5)
ag-solo_1  |   at meteredConstructor.doKernelSyscall (packages/SwingSet/src/kernel/kernelSyscall.js:144:16)
ag-solo_1  |   at vatSyscallHandler (packages/SwingSet/src/kernel/kernel.js:665:43)
ag-solo_1  |   at syscallFromWorker (packages/SwingSet/src/kernel/vatManager/manager-helper.js:196:18)
ag-solo_1  |   at doSyscall (packages/SwingSet/src/kernel/vatManager/supervisor-helper.js:128:11)
ag-solo_1  |   at meteredConstructor.resolve (packages/SwingSet/src/kernel/vatManager/supervisor-helper.js:161:29)
ag-solo_1  |   at eval (packages/SwingSet/src/kernel/liveSlots.js:686:15)
ag-solo_1  |
```

Error after opening the Agoric wallet URL.
```
ag-solo_1  | 2021-05-12T02:29:34.207Z web: 192.168.0.1:63694[3]: inbound error: (Error#4) from {
ag-solo_1  |   "type": "CTP_BOOTSTRAP",
ag-solo_1  |   "epoch": 0,
ag-solo_1  |   "questionID": 1,
ag-solo_1  |   "error": "kernel panic kp40.policy panic: rejected {\"body\":\"{\\\"@qclass\\\":\\\"error\\\",\\\"errorId\\\":\\\"error:liveSlots:v5#70001\\\",\\\"message\\\":\\\"vat terminated\\\",\\\"name\\\":\\\"Error\\\"}\",\"slots\":[]}",
ag-solo_1  |   "meta": {
ag-solo_1  |     "channelID": 3,
ag-solo_1  |     "dispatcher": "onError",
ag-solo_1  |     "origin": "http://127.0.0.1:8000",
ag-solo_1  |     "query": {
ag-solo_1  |       "isQuery": true
ag-solo_1  |     },
ag-solo_1  |     "url": "/private/captp",
ag-solo_1  |     "date": 1620786574205
ag-solo_1  |   }
ag-solo_1  | }
ag-solo_1  | 2021-05-12T02:29:34.217Z web: 192.168.0.1:63694[3]: client closed
ag-solo_1  | 2021-05-12T02:29:34.219Z web: 192.168.0.1:63694[3]: inbound error: (Error#4) from {
ag-solo_1  |   "type": "ws/meta",
ag-solo_1  |   "meta": {
ag-solo_1  |     "channelID": 3,
ag-solo_1  |     "dispatcher": "onClose",
ag-solo_1  |     "origin": "http://127.0.0.1:8000",
ag-solo_1  |     "query": {
ag-solo_1  |       "isQuery": true
ag-solo_1  |     },
ag-solo_1  |     "url": "/private/captp",
ag-solo_1  |     "date": 1620786574218
ag-solo_1  |   }
ag-solo_1  | }
ag-solo_1  | UnhandledPromiseRejectionWarning: kernel panic kp40.policy panic: rejected {"body":"{\"@qclass\":\"error\",\"errorId\":\"error:liveSlots:v5#70001\",\"message\":\"vat terminated\",\"name\":\"Error\"}","slots":[]}
```

**Comment by kaustubhkapatral** [comment]
I'm also running into the same issue. Here are my logs 
[logs.txt](https://github.com/Agoric/dapp-treasury/files/6464031/logs.txt)

**Comment by rakhmanovr** [comment]
same error for me.

**Comment by PavelMoneyin** [comment]
Instal new software - same issue.

**Comment by dayakarreddyn** [comment]
This problem is only with incentivized testnet docker yaml file. [docker-compose.yml](https://testnet.agoric.net/docker-compose.yml)
The dev yaml works fine.

**Comment by bananooo-zhang** [comment]
same
